package com.madlyai.domain;
// Generated 2018-12-23 17:32:46 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * FeBank generated by hbm2java
 */
@Entity
@Table(name = "fe_bank")
public class FeBank implements java.io.Serializable {

	private String bankSn;
	private String bankDesc;

	public FeBank() {
	}

	public FeBank(String bankSn) {
		this.bankSn = bankSn;
	}

	public FeBank(String bankSn, String bankDesc) {
		this.bankSn = bankSn;
		this.bankDesc = bankDesc;
	}

	@Id

	@Column(name = "bank_sn", unique = true, nullable = false)
	public String getBankSn() {
		return this.bankSn;
	}

	public void setBankSn(String bankSn) {
		this.bankSn = bankSn;
	}

	@Column(name = "bank_desc", length = 80)
	public String getBankDesc() {
		return this.bankDesc;
	}

	public void setBankDesc(String bankDesc) {
		this.bankDesc = bankDesc;
	}

}
